### ISSUE TITLE
PFDATA for Carbon PS2 Demo seems incomplete

### ISSUE THREAD

**Issue by antoniu200** [Ekey/NFS.BIN.Tool#2]
Hi,

I just tried your program on the Carbon PS2 Demo and it has not extracted anything in the PFDATA folder, although the correct files exist and your FileNames.list contains quite a few posibilities for .mus and .mpf pairs. However, none of them are correct for the PS2 Demo, since the file name for the .mus and .mpf needs to be identical and Demo only has one of each.

I have downloaded my Demo from here: https://archive.org/details/NeedForSpeedCarbonUSASLUS29193

Now, I have identified the corresponding files for both .mus and .mpf:
05832668 is the .mus file
36407D66 is the .mpf file

I tried moving both to SOUND\PFDATA and renaming both to cb_mus, with the correct extension for both, and the music was openable in foobar2000 with vgmstream plugin.

My question is now: Is there any reference in any ZZDATA file? I have not identified any in ZDIR.BIN, but I may not have looked close enough. Could you please take a look for yourself and update the program as necessary?

Thank you!

**Comment by Ekey** [comment]
I checked and it works fine.

![Screenshot_1](https://github.com/Ekey/NFS.BIN.Tool/assets/1664144/297f5f0b-4be9-47d1-b180-a014e8a4918d)
![Screenshot_2](https://github.com/Ekey/NFS.BIN.Tool/assets/1664144/fe7c85bc-3539-4c48-bbf7-6c207b8d424f)

and files in unpacked folder.
![Screenshot_3](https://github.com/Ekey/NFS.BIN.Tool/assets/1664144/8e1d460d-20ff-4074-b6e3-4ec69a4fe2e5)

**Comment by Ekey** [comment]
1) As i see you are use old version of my tool -> 0.0.1.3318 with project list 8098, redownload 39920 build from release section and try again.
2) ZDIR & ZZDATA don't contain names, only their hashes
3) The names are absolutely correct. You can rename it however you need. My list contains only the names that I could find.

> In any case, I believe my issue is fairly simple to reproduce. I am aware that you already tested on some Carbon PS2 Demo build, but please download the one I linked above and test that way.

I tested on your demo build :)

**Comment by antoniu200** [comment]
Okay, I see you updated the latest build, thank you for that.
Now the tool does extract the correct MUS file, but the MPF is wrong. MPF files have a 4 letter header: xDFP. The file extracted by the tool does not have it. I executed your script 3 times, but the file extracted is the same wrong file: it seems like something related to Autosculpt.

If it means something helpful to you, __Unknown\36407D66 was the MPF file when the previous version of the script was executed. This script mixes it up with the autosculpt file and no MPF file is present in __Unknown either.

**Comment by antoniu200** [comment]
Update: I just checked the MUS file too. That one is also wrong now. It was correct in the older script: __Unknown\05832668.
What is strange is that both wrong files are the correct size.

**Comment by Ekey** [comment]
> Now the tool does extract the correct MUS file, but the MPF is wrong. MPF files have a 4 letter header: xDFP. The file extracted by the tool does not have it. I executed your script 3 times, but the file extracted is the same wrong file: it seems like something related to Autosculpt.

Fixed ([0.2.25804](https://github.com/Ekey/NFS.BIN.Tool/releases/download/0.1/NFS.BIN.Tool-0.2.25804.zip))

**Comment by antoniu200** [comment]
Tested, working
