### ISSUE TITLE
specify ZDIR.BIN (Need For Speed Underground)

### ISSUE THREAD

**Issue by Izaise** [Ekey/NFS.BIN.Tool#3]
When I try to extract the files (TEXTURES.BIN) I get the error
[ERROR]: You must specify ZDIR.BIN fle for extract files!
I'm not really sure what to do or what does it mean
command I used:
NFS.Unpacker.exe "[location[/TEXTURES.BIN" "[Output folder]"

**Comment by Ekey** [comment]
You need to specify the path to the ZDIR.BIN file.

Example usage : `NFS.Unpacker.exe "E:\Games\NFS\ZDIR.BIN"`

**Comment by Izaise** [comment]
I already specified it but it keeps giving me an error

**Comment by Ekey** [comment]
What platform?

**Comment by Izaise** [comment]
Linux

**Comment by Ekey** [comment]
Probably the Linux version does not use the ZZ filesystem. Try this project > https://github.com/SpeedReflect/Binary
