### ISSUE TITLE
[Feature Request] Support for Need for Speed: Hot Pursuit 2 (PS2)

### ISSUE THREAD

**Issue by mrmaller1905** [Ekey/NFS.BIN.Tool#8]
Can you add support for Need for Speed: Hot Pursuit 2 (PS2) to your unpacker?

**Comment by Ekey** [comment]
Added https://github.com/Ekey/NFS.BIN.Tool/releases/tag/0.4

**Comment by mrmaller1905** [comment]
What program or DLL hook did you use to log filenames from ZDIR.BIN or ZZDATA.BIN of Need for Speed Hot Pursuit 2 for the PlayStation 2?
